name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install hexo@7.2.0 hexo-cli --save
        npm install

    - name: Hexo Clean and Generate
      run: |
        npx hexo clean
        npx hexo generate

    - name: Add CNAME
      run: |
        echo "www.touhouchronicle.com" > ./public/CNAME

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Matcha8520'
        git config --global user.email 'mr_matcha@outlook.com'
        
        # 使用 Personal Access Token 进行推送
        git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/Matcha8520/Matcha8520.github.io .deploy_git
        cp -r public/* .deploy_git
        cd .deploy_git
        git add -A
        git commit -m "Deployed by GitHub Actions" || echo "No changes to commit"
        git push origin main
